[features]
seeds = false
skip-lint = false

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/edujlac/.config/solana/id.json"
#cluster = "mainnet"
#wallet = "/Users/edujlac/WebstormProjects/thekings-raffle/raffles.json"

[programs.localnet]
#thekings_raffle_sc = "4v5UTAWBMA4qyA5YjmnHeHk4g88HKffRYG6mdbX7pxfL"
thekings_raffle_sc = "EVakesLUYmAAf8wrzLByEScNnmQrUJE7Hgzcsypj7bk5"

[programs.devnet]
#thekings_raffle_sc = "4v5UTAWBMA4qyA5YjmnHeHk4g88HKffRYG6mdbX7pxfL"
thekings_raffle_sc = "EVakesLUYmAAf8wrzLByEScNnmQrUJE7Hgzcsypj7bk5"

[programs.mainnet]
thekings_raffle_sc = "EVakesLUYmAAf8wrzLByEScNnmQrUJE7Hgzcsypj7bk5"

[scripts]
test = "yarn run ts-mocha -t 1000000 tests/*.ts"
#test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"
